---
title: azat at github
description: ""
google_analytics: G-B0QQGN4BYM
show_downloads: false
# Use the latest version of the theme via jekyll-remote-theme, this is required for GA4 [1].
#   [1]: https://github.com/jekyll/minima/issues/561
remote_theme: jekyll/minima

gems:
  - jekyll-remote-theme
  - jekyll-mentions
